.\" $Id: rseq.1,v 1.5 1999/05/05 09:15:16 garbled Exp $
.\" Copyright (c) 1998
.\"	Tim Rightnour.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgment:
.\"	This product includes software developed by Tim Rightnour.
.\" 4. The name of Tim Rightnour may not be used to endorse or promote 
.\"    products derived from this software without specific prior written 
.\"    permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY TIM RIGHTNOUR ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL TIM RIGHTNOUR BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" The following requests are required for all man pages.
.Dd December 14, 1998
.Dt SEQ 1
.Sh NAME
.Nm seq
.Nd run a command on a cluster in sequence
.Sh SYNOPSIS
.Nm
.Op Fl aeiq
.Op Fl g Ar rungroup1,...,rungroupN
.Op Fl l Ar username
.Op Fl w Ar node1,...,nodeN
.Op Fl x Ar node1,...,nodeN
.Op Ar command ...
.Sh DESCRIPTION
The 
.Nm
utility can be used to run a command, or group of commands on a cluster of 
machines.  The command or commands are run on a single node in the cluster,
which is incremented in sequence on each invocation of
.Nm
The following options are available:
.Bl -tag -width www
.It Fl a
The
.Fl a
option modifies the behavior of seq when dealing with stdin.  Normally 
all commands from stdin are run on the same machine.  Specifying the
.Fl a
option causes each command to be run on the next node in the seqence.
.It Fl e
Unless the
.Fl e
option is specified, stderr from remote commands will not be reported to the user.
.It Fl i
The
.Fl i
option will list information about the current cluster, and command groupings.
It will also show you which command you are about to run, and your username if
specified with the
.Fl l
option.
.It Fl q
The
.Fl q
option does not issue any commands, but displays information about the cluster.
.It Fl g
If the
.Fl g
option is specified, followed by a comma separated list of group names, the command will only be run on that group
of nodes.  A node may be a part of more than one group if desired, however running without the
.Fl g
option will run the command on the same node as many times as it appears in the
file specified by the
.Ev CLUSTER
environment variable.  This option is silently ignored if used with the
.Fl w
option.
.It Fl l
If the
.Fl l
option is specified, followed by a username, the commands will be run under that
userid on the remote machines.  Consideration must be taken for proper authentication, 
for this to work.
.It Fl w
If the
.Fl w
option is specified, followed by a comma delimited list of machine names,
the
.Ar command
will be run on each node in the list.  Without this option,
.Nm
runs on the nodes listed in the file pointed to by the
.Ev CLUSTER
environment variable.
.It Fl x
The
.Fl x
option can be used to exclude specific nodes from the cluster.  The format is the same as
the
.Fl w
option, a comma delimited list of machine names.  This option is silently ignored if used with the
.Fl w
option.
.Sh ENVIRONMENT
.Nm
utilizes the following environment variables.
.Bl -tag -width "RCMD_CMD"
.It Ev CLUSTER
Contains a filename, which is a newline separated list of nodes
in the cluster.
.It Ev RCMD_CMD
Command to use to connect to remote machines.  The command chosen must
be able to connect with no password to the remote host.  Defaults to
.Ic rsh
.It Ev SEQ_FILE
Specifies a specific sequence file.  This is a temporary file, which saves
the number of the last node run on.  It defaults to /tmp/[pid].seq.  Where [pid]
is the pid of the parent process of seq.  It may be useful to wire the SEQ_FILE to
a particular file, in order to keep proper sequence when invoking seq from subshells
or scripts.
.\" .Sh FILES
.Sh DIAGNOSTICS
Exit status is 0 on success, 1 if an error occurs.
.Sh SEE ALSO
.Xr dsh 1 ,
.Xr rsh 1 ,
.Xr kerberos 3 ,
.Xr hosts.equiv 5 ,
.Xr rhosts 5
.Sh HISTORY
The
.Nm
command appeared in clusterit 1.1.
.Sh AUTHOR
.Nm Seq
was written by Tim Rightnour.
.Sh BUGS
Error handling could use some work.
.Pp
The maximum number of nodes in a cluster is hardwired to 512.  This
can be modified by recompiling the program.
.Pp
The
.Nm
command works fine when used with the
.Fl w
and
.Fl x
flags.  However the user may find that if the arguments are changed, or
the flags are omitted on a subsequent run, the next node picked may not be
predictable.  The sequence is calculated on each invocation of
.Nm
and the sequence numbers recorded in the temporary file may not match up
to a new sequence placed on the command line.
